[package]
name = "rust_app_one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_lib_one = { path = "../../packages/rust-lib-one" }
rust_lib_two = { path = "../../packages/rust-lib-two" }